version: '3'

services:
  db:
    image: mongo
    container_name: bingo-mongodb
    restart: always
    volumes:
      - ./db:/data/db

  backend:
    build:
      context: ./backend
    container_name: bingo-backend
    restart: always
    volumes:
      - ./backend/cards.csv:/app/cards.csv
    depends_on:
      - db
    links:
      - db
    ports:
      - 8999:8999

  frontend:
    image: nginx:alpine
    container_name: bingo-frontend
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:80
